export let product = [
    {
        "id": 1,
        "nombre": "Taladro Percutor 800W",
        "categoria": "Herramientas eléctricas",
        "marca": "Bosch",
        "modelo": "PSB 800",
        "precio": 450,
        "costo": 320,
        "stock": 24,
        "unidad": "unidad",
        "proveedor_id": 1,
        "codigo_barras": "7891234567890",
        "activo": true
    },
    {
        "id": 2,
        "nombre": "Pintura Latex Blanco 1 galón",
        "categoria": "Pinturas",
        "marca": "Sherwin Williams",
        "modelo": "Ultra",
        "precio": 180,
        "costo": 120,
        "stock": 45,
        "unidad": "galón",
        "proveedor_id": 2,
        "codigo_barras": "7891234567891",
        "activo": true
    },
    {
        "id": 3,
        "nombre": "Tornillo Phillips 3/4 pulgada",
        "categoria": "Fijaciones",
        "marca": "TornillosCA",
        "modelo": "TP-75",
        "precio": 1.5,
        "costo": 0.9,
        "stock": 5000,
        "unidad": "unidad",
        "proveedor_id": 3,
        "codigo_barras": "7891234567892",
        "activo": true
    },
    {
        "id": 4,
        "nombre": "Cable Eléctrico 12 AWG 100 m",
        "categoria": "Eléctricos",
        "marca": "ElectroNorte",
        "modelo": "CN-12",
        "precio": 320,
        "costo": 240,
        "stock": 18,
        "unidad": "rollo",
        "proveedor_id": 4,
        "codigo_barras": "7891234567893",
        "activo": true
    },
    {
        "id": 5,
        "nombre": "Llave Inglesa 10 pulgadas",
        "categoria": "Herramientas manuales",
        "marca": "Stanley",
        "modelo": "SW-10",
        "precio": 85,
        "costo": 55,
        "stock": 33,
        "unidad": "unidad",
        "proveedor_id": 1,
        "codigo_barras": "7891234567894",
        "activo": true
    },
    {
        "id": 6,
        "nombre": "Tubo PVC 1/2 pulgada x 6 m",
        "categoria": "Plomería",
        "marca": "Plomerialux",
        "modelo": "TPVC-05",
        "precio": 45,
        "costo": 30,
        "stock": 120,
        "unidad": "unidad",
        "proveedor_id": 5,
        "codigo_barras": "7891234567895",
        "activo": true
    },
    {
        "id": 7,
        "nombre": "Martillo de Carpintero 16 oz",
        "categoria": "Herramientas manuales",
        "marca": "Irwin",
        "modelo": "M16",
        "precio": 60,
        "costo": 40,
        "stock": 40,
        "unidad": "unidad",
        "proveedor_id": 1,
        "codigo_barras": "7891234567896",
        "activo": true
    },
    {
        "id": 8,
        "nombre": "Pegamento para PVC 200 ml",
        "categoria": "Plomería",
        "marca": "Plomerialux",
        "modelo": "PVC-200",
        "precio": 35,
        "costo": 22,
        "stock": 67,
        "unidad": "frasco",
        "proveedor_id": 5,
        "codigo_barras": "7891234567897",
        "activo": true
    },
    {
        "id": 9,
        "nombre": "Destornillador Phillips #2",
        "categoria": "Herramientas manuales",
        "marca": "Stanley",
        "modelo": "DS-2",
        "precio": 25,
        "costo": 15,
        "stock": 75,
        "unidad": "unidad",
        "proveedor_id": 1,
        "codigo_barras": "7891234567898",
        "activo": true
    },
    {
        "id": 10,
        "nombre": "Interruptor Termomagnético 20A",
        "categoria": "Eléctricos",
        "marca": "ElectroNorte",
        "modelo": "IT-20",
        "precio": 75,
        "costo": 50,
        "stock": 34,
        "unidad": "unidad",
        "proveedor_id": 4,
        "codigo_barras": "7891234567899",
        "activo": true
    }
]